spring:
  main:
    banner-mode: "off"
  mvc:
    favicon:
      enabled: false
    locale-resolver: fixed
    locale: fr
logging:
  level:
    root: warn
    ca:
      expertus: info
expertus:
  game:
    maxPersons: 30


